### PR TITLE
feat: bump golang to v1.21

### PR DESCRIPTION
**Pull request by FrankYang0529**
https://github.com/harvester/harvester/issues/5310

### CODE REVIEW

**Review by ibrokethecloud — COMMENTED** [review]
we should update golangci-lint to v1.57.1. The current version hangs in ci and eventually errors out. eg: https://github.com/harvester/vm-import-controller/blob/main/Dockerfile.dapper#L17C93-L17C106

**Review by starbops — COMMENTED** [review]
I'm unable to build the artifacts due to the unexpected error reported by the validate script:

```
Running validation
Running: golangci-lint run
./scripts/validate: line 18:    11 Killed                  golangci-lint run
FATA[0074] exit status 137                              
make: *** [validate] Error 1
```

By monitoring the resource usage of the build machine, it seems that `golangci-lint` uses tremendous amount of memory:

SCR-20240418-oiuc

I'm not sure if it's my own environmental problem.

---

Update: Gaurav just answered my question above :P

**Review by starbops — COMMENTED** [review]
```
Running validation
Running: golangci-lint run
?   	github.com/harvester/seeder	[no test files]
?   	github.com/harvester/seeder/pkg/api/v1alpha1	[no test files]
?   	github.com/harvester/seeder/pkg/bindata	[no test files]
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.21 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="go1.21" set. Notably, if go1.21 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
	/go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20230204201903-c31fa085b70e/untested.go:25 +0x1da
FAIL	github.com/harvester/seeder/pkg/controllers	0.005s
```

Might also need to bump `go4.org/unsafe/assume-no-moving-gc`.

**Comment by FrankYang0529** [comment]
Hi @starbops, thank you. I update the package and run `make test` without error.

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Pull request merged**
